module.exports = {
  modules: {
    'geoportal-utils': {},
    'geoportal-tasks': {},
    'geoportal-launder': {},
    'geoportal-i18n': {},
    'geoportal-db': {},
    'geoportal-locks': {},
    'geoportal-caches': {},
    'geoportal-migrations': {},
    'geoportal-express': {},
    'geoportal-urls': {},
    'geoportal-templates': {},
    'geoportal-email': {},
    'geoportal-push': {},
    'geoportal-permissions': {},
    'geoportal-assets': {},
    'geoportal-admin-bar': {},
    'geoportal-login': {},
    // After login, so it can install the CSRF middleware exported by geoportal-express and still have it
    // be able to check req.user first
    'geoportal-csrf': {},
    'geoportal-notifications': {},
    'geoportal-browser-utils': {},
    'geoportal-ui': {},
    'geoportal-schemas': {},
    'geoportal-docs': {},
    'geoportal-jobs': {},
    'geoportal-versions': {},
    'geoportal-tags': {},
    'geoportal-modal': {},
    'geoportal-attachments': {},
    'geoportal-oembed': {},
    'geoportal-pager': {},
    // global comes first so it can register a doc type manager and clean things up before
    // pages claims any orphan page types
    'geoportal-global': {},
    'geoportal-polymorphic-manager': {},
    'geoportal-pages': {},
    'geoportal-search': {},
    'geoportal-any-page-manager': {},
    'geoportal-areas': {},
    'geoportal-rich-text-widgets': {},
    'geoportal-html-widgets': {},
    'geoportal-video-fields': {},
    'geoportal-video-widgets': {},
    'geoportal-groups': {},
    'geoportal-users': {},
    'geoportal-images': {},
    'geoportal-images-widgets': {},
    'geoportal-files': {},
    'geoportal-files-widgets': {},
    'geoportal-soft-redirects': {},
    // ALWAYS LAST FOREVER
    'geoportal-service-bridge': {}
  }
};
